TOKEN = 'YOUR_DISCORD_TOKEN'

PREFIX = '/'
API_KEY = 'YOUR_API_KEY'
GUILD_ID = 
WELCOME_CHANNEL_ID = 
LOGS_CHANNEL_ID = 
IPDATA_API_KEY = "Your IPDATA_API_KEY"
GUEST_ROLE_ID = 
BOT_COMMANDER_ROLE_ID = 
BANNED_ROLE_ID = 
NEWS_CHANNEL_ID = 
